### ISSUE TITLE
Missing Pretrained Model Checkpoint Files

### ISSUE THREAD

**Issue by JERRY41173** [Jyxarthur/flowsam#1]
Hello, I'm currently trying to replicate your project and encountered an issue where the pretrained model checkpoint files are missing. Specifically, the files `sam_vit_h_4b8939.pth` and `sam_vit_b_01ec64.pth` are referenced in the code but not available in the repository or via any provided links.

Could you please provide these files or update the repository with links to download them? This would be incredibly helpful for anyone trying to use or contribute to the project.

Thank you for your great work on this project, and I look forward to your response.
![image](https://github.com/Jyxarthur/flowsam/assets/167638611/c2469d14-8ff9-497e-8f4e-ae197f8ee149)
![image](https://github.com/Jyxarthur/flowsam/assets/167638611/e9cdb35b-741b-4854-a00c-fcb50961e943)

**Comment by Jyxarthur** [comment]
Hi, thanks for your interest in our work. 
The checkpoints mentioned are the official SAM ckpts, which can be found in their [official repo](https://github.com/facebookresearch/segment-anything/) under the Section "Model Checkpoints".
