### ISSUE TITLE
how to get "FlowImages_gap-2"? I only get FlowImages_gap-1 after run_inference.py

### ISSUE THREAD

**Issue by WuJuli** [Jyxarthur/flowsam#11]
![image](https://github.com/user-attachments/assets/678e949d-dbb4-490f-b71f-8141f0fedbd7)

**Comment by Jyxarthur** [comment]
Please set the gap to [1, 2] in `flow/run_inference.py` in order to get flows for both gaps 1 and 2
https://github.com/Jyxarthur/flowsam/blob/57c5c40c92c73fd3244631409610c4b2ec1d5097/flow/run_inference.py#L10
If gap 1 flows are already obtained, set gap = [2] instead

**Comment by WuJuli** [comment]
OIS, thank you!!
