### ISSUE TITLE
Where is flow folder?

### ISSUE THREAD

**Issue by zhengqili** [Jyxarthur/flowsam#3]
Great work! But in READNE it mentioned "In this work, optical flow is estimated by [RAFT] (https://github.com/princeton-vl/RAFT), with the code provided in the flow folder.". But somehow I am not able to find the flow folder. Do I miss something here?

**Comment by Jyxarthur** [comment]
Thanks for pointing this out. The flow folder has now added to the repo.

**Comment by zhengqili** [comment]
Thank you!
