### ISSUE TITLE
How to fill in "val_seq"?

### ISSUE THREAD

**Issue by fuzhaiping** [Jyxarthur/flowsam#9]
When write "None", Program error.

**Comment by Jyxarthur** [comment]
Hi, thanks for your interest in our work. 

When specifying `val_seq = None`, the sequence list would be automatically initialised in the corresponding dataloader. For example, please refer to L34 to L51 in `data/dataloaders/dvs_loader.py`.

If you are loading your own dataset via `data/dataloaders/example_loader.py`, no default sequence list is given. Then, the `val_seq` is needed to be manually specified as the list of sub-directories in your dataset folder.

**Comment by fuzhaiping** [comment]
Thank you very much for your reply!
